//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epilation.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblcustomer()
        {
            this.tblservicerendereds = new HashSet<tblservicerendered>();
        }
    
        public int CustomerID { get; set; }
        public string CustFirstName { get; set; }
        public string CustLastName { get; set; }
        public string CustPhoneNumber { get; set; }
        public string CustStreet { get; set; }
        public string CustGender { get; set; }
        public Nullable<bool> Durumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblservicerendered> tblservicerendereds { get; set; }
    }
}
