//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epilation.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblemployee()
        {
            this.tblservicerendereds = new HashSet<tblservicerendered>();
        }
    
        public int EmployeeID { get; set; }
        public int ServiceID { get; set; }
        public string EmpFirstName { get; set; }
        public string EmpLastName { get; set; }
        public string EmpPhoneNumber { get; set; }
        public string EmpStreet { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<bool> Durumu { get; set; }
        public string JobDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblservicerendered> tblservicerendereds { get; set; }
        public virtual tblservice tblservice { get; set; }
    }
}
