//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epilation.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblservicerendered
    {
        public int AppointmentID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<decimal> ServiceExtendedPrice { get; set; }
        public int EmployeeID { get; set; }
        public int CustomerID { get; set; }
    
        public virtual tblcustomer tblcustomer { get; set; }
        public virtual tblemployee tblemployee { get; set; }
    }
}
